version: '3.8'

services:
  composer:
    image: composer:2.2
    volumes:
      - .:/app

  php:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app

  phpunit:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
